import {
  House, Settings, ArrowLeft, ArrowRight, Plus, X, Heart, Star, User, Search, Menu, Bell,
  ShoppingCart, Share2, Play, Pause, Check, ChevronLeft, ChevronRight, ChevronUp, ChevronDown,
  Trash2, Pencil, Camera, Image, Video, Music, Mail, Phone, MessageCircle, Send, Calendar, Clock,
  MapPin, Globe, Lock, Eye, EyeOff, Download, Upload, RefreshCw, LogOut, LogIn, Filter, List,
  LayoutGrid, Layers, Bookmark, Tag, Gift, CreditCard, Wallet, ThumbsUp, Sun, Moon, Cloud, Zap,
  Wifi, Volume2, Mic, File, Folder, Copy, Link, ExternalLink, Info, TriangleAlert, CircleCheck,
  CircleX, Trophy, Gamepad2, Sparkles, ShoppingBag, Rocket, Flame, Coffee, Compass,
  MoreHorizontal, Settings2, SlidersHorizontal, Power, Map as MapIcon, type LucideIcon,
} from 'lucide-react'

export interface IconDef {
  id: string // official Lucide kebab-case name
  comp: LucideIcon
}

// The first entries are the pinned "frequently used" icons.
const defs: IconDef[] = [
  { id: 'house', comp: House },
  { id: 'settings', comp: Settings },
  { id: 'arrow-left', comp: ArrowLeft },
  { id: 'arrow-right', comp: ArrowRight },
  { id: 'plus', comp: Plus },
  { id: 'x', comp: X },
  { id: 'heart', comp: Heart },
  { id: 'star', comp: Star },
  { id: 'user', comp: User },
  { id: 'search', comp: Search },
  { id: 'menu', comp: Menu },
  { id: 'bell', comp: Bell },
  { id: 'shopping-cart', comp: ShoppingCart },
  { id: 'share-2', comp: Share2 },
  { id: 'play', comp: Play },
  { id: 'pause', comp: Pause },
  // --- searchable library ---
  { id: 'check', comp: Check },
  { id: 'chevron-left', comp: ChevronLeft },
  { id: 'chevron-right', comp: ChevronRight },
  { id: 'chevron-up', comp: ChevronUp },
  { id: 'chevron-down', comp: ChevronDown },
  { id: 'trash-2', comp: Trash2 },
  { id: 'pencil', comp: Pencil },
  { id: 'camera', comp: Camera },
  { id: 'image', comp: Image },
  { id: 'video', comp: Video },
  { id: 'music', comp: Music },
  { id: 'mail', comp: Mail },
  { id: 'phone', comp: Phone },
  { id: 'message-circle', comp: MessageCircle },
  { id: 'send', comp: Send },
  { id: 'calendar', comp: Calendar },
  { id: 'clock', comp: Clock },
  { id: 'map-pin', comp: MapPin },
  { id: 'globe', comp: Globe },
  { id: 'lock', comp: Lock },
  { id: 'eye', comp: Eye },
  { id: 'eye-off', comp: EyeOff },
  { id: 'download', comp: Download },
  { id: 'upload', comp: Upload },
  { id: 'refresh-cw', comp: RefreshCw },
  { id: 'log-out', comp: LogOut },
  { id: 'log-in', comp: LogIn },
  { id: 'filter', comp: Filter },
  { id: 'list', comp: List },
  { id: 'layout-grid', comp: LayoutGrid },
  { id: 'layers', comp: Layers },
  { id: 'bookmark', comp: Bookmark },
  { id: 'tag', comp: Tag },
  { id: 'gift', comp: Gift },
  { id: 'credit-card', comp: CreditCard },
  { id: 'wallet', comp: Wallet },
  { id: 'thumbs-up', comp: ThumbsUp },
  { id: 'sun', comp: Sun },
  { id: 'moon', comp: Moon },
  { id: 'cloud', comp: Cloud },
  { id: 'zap', comp: Zap },
  { id: 'wifi', comp: Wifi },
  { id: 'volume-2', comp: Volume2 },
  { id: 'mic', comp: Mic },
  { id: 'file', comp: File },
  { id: 'folder', comp: Folder },
  { id: 'copy', comp: Copy },
  { id: 'link', comp: Link },
  { id: 'external-link', comp: ExternalLink },
  { id: 'info', comp: Info },
  { id: 'triangle-alert', comp: TriangleAlert },
  { id: 'circle-check', comp: CircleCheck },
  { id: 'circle-x', comp: CircleX },
  { id: 'trophy', comp: Trophy },
  { id: 'gamepad-2', comp: Gamepad2 },
  { id: 'sparkles', comp: Sparkles },
  { id: 'shopping-bag', comp: ShoppingBag },
  { id: 'rocket', comp: Rocket },
  { id: 'flame', comp: Flame },
  { id: 'coffee', comp: Coffee },
  { id: 'compass', comp: Compass },
  { id: 'map', comp: MapIcon },
  { id: 'more-horizontal', comp: MoreHorizontal },
  { id: 'settings-2', comp: Settings2 },
  { id: 'sliders-horizontal', comp: SlidersHorizontal },
  { id: 'power', comp: Power },
]

export const ALL_ICONS = defs
export const PINNED_ICONS = defs.slice(0, 16)
const ICON_MAP = new Map(defs.map((d) => [d.id, d.comp]))

export const getIconComp = (id?: string): LucideIcon | undefined => (id ? ICON_MAP.get(id) : undefined)
export const DEFAULT_ICON = 'house'
